export const COLORS = [
  {
    value: "black-and-white",
    name: "Black and White",
    backgroundColor: "#000",
    foregroundColor: "#fff",
  },
  {
    value: "red",
    name: "Red",
    backgroundColor: "#FF0000",
    foregroundColor: "#fff",
  },
  {
    value: "yellow",
    name: "Yellow",
    backgroundColor: "#FBE854",
    foregroundColor: "#000",
  },
  {
    value: "pink",
    name: "Pink",
    backgroundColor: "#FB81CD",
    foregroundColor: "#000",
  },
  {
    value: "violet",
    name: "Violet",
    backgroundColor: "#B82C83",
    foregroundColor: "#fff",
  },
  {
    value: "gold",
    name: "Gold",
    backgroundColor: "#DAA520",
    foregroundColor: "#000",
  },
  {
    value: "orange",
    name: "Orange",
    backgroundColor: "#F7923A",
    foregroundColor: "#000",
  },
  {
    value: "darkviolet",
    name: "Dark Violet",
    backgroundColor: "#642B7F",
    foregroundColor: "#fff",
  },
  {
    value: "lightgreen",
    name: "Light Green",
    backgroundColor: "#BCCC46",
    foregroundColor: "#000",
  },
  {
    value: "lightblue",
    name: "Light Blue",
    backgroundColor: "#C2D5F1",
    foregroundColor: "#000",
  },
  {
    value: "darkblue",
    name: "Dark Blue",
    backgroundColor: "#0A1AB4",
    foregroundColor: "#fff",
  },
  {
    value: "darkorange",
    name: "Dark Orange",
    backgroundColor: "#612A00",
    foregroundColor: "#fff",
  },
  {
    value: "darkgreen",
    name: "Dark Green",
    backgroundColor: "#004600",
    foregroundColor: "#fff",
  },
]
