nodeLinker: node-modules

npmMinimalAgeGate: 1440 # 1 day in minutes (24 * 60)

npmPreapprovedPackages:
  [
    "@artsy/cohesion",
    "@artsy/express-reloadable",
    "@artsy/img",
    "@artsy/morgan",
    "@artsy/multienv",
    "@artsy/to-title-case",
    "@artsy/update-repo",
    "@artsy/xapp",
  ]

yarnPath: .yarn/releases/yarn-4.12.0.cjs

enableScripts: false # Disable postinstall scripts from 3rd parties
