endpoint: http://localhost:5001/v2
transport:
  type: streamable_http
operations:
  source: local
  paths:
    - ./mcp/operations/llmSystemContext.graphql
    - ./mcp/operations/analytics
    - ./mcp/operations/artist
schema:
  source: local
  path: ./_schemaV2.graphql
overrides:
  mutation_mode: "all" # enable mutations!
introspection:
  execute:
    enabled: true
  introspect:
    enabled: true
  search:
    enabled: true
headers:
  "x-access-token": "fill-in"
  "x-user-id": "fill-in"
