import { GraphQLString, GraphQLBoolean } from "graphql"
import { mutationWithClientMutationId } from "graphql-relay"
import { ArtistType } from "schema/v2/artist/index"
import PopularArtists from "schema/v2/artists/popular"
import { ResolverContext } from "types/graphql"

export default mutationWithClientMutationId<any, any, ResolverContext>({
  name: "FollowArtist",
  description: "Follow (or unfollow) an artist",
  inputFields: {
    artistID: {
      type: GraphQLString,
    },
    unfollow: {
      type: GraphQLBoolean,
      defaultValue: false,
    },
  } /*
  FIXME: Generated by the snake_case to camelCase codemod.
         Either use this to fix inputs and/or remove this comment.
  {
    const {
      artistID,
      ..._newFields
    } = newFields;
    const oldFields = {
      artistID: artist_id,
      ..._newFields
    };
  }
  */,
  outputFields: {
    artist: {
      type: ArtistType,
      resolve: ({ artist_id }, _options, { artistLoader }) =>
        artistLoader(artist_id),
    },
    popularArtists: PopularArtists,
  },
  mutateAndGetPayload: (
    { artistID: artist_id, unfollow },
    { followArtistLoader, unfollowArtistLoader }
  ) => {
    if (!followArtistLoader || !unfollowArtistLoader) {
      return new Error("You need to be signed in to perform this action")
    }

    let performAction: Promise<any>
    if (unfollow) {
      performAction = unfollowArtistLoader(artist_id)
    } else {
      performAction = followArtistLoader({ artist_id })
    }

    // FIXME: Object is possibly 'null'
    // @ts-ignore
    return performAction.then(() => ({ artist_id }))
  },
})
