import { GraphQLString, GraphQLBoolean } from "graphql"
import { mutationWithClientMutationId } from "graphql-relay"
import { ProfileType } from "schema/v2/profile"
import { ResolverContext } from "types/graphql"

export default mutationWithClientMutationId<any, any, ResolverContext>({
  name: "FollowProfile",
  description: "Follow (or unfollow) a profile",
  inputFields: {
    profileID: {
      type: GraphQLString,
    },
    unfollow: {
      type: GraphQLBoolean,
      defaultValue: false,
    },
  } /*
  FIXME: Generated by the snake_case to camelCase codemod.
         Either use this to fix inputs and/or remove this comment.
  {
    const {
      profileID,
      ..._newFields
    } = newFields;
    const oldFields = {
      profileID: profile_id,
      ..._newFields
    };
  }
  */,
  outputFields: {
    profile: {
      type: ProfileType,
      resolve: ({ profile_id }, _options, { profileLoader }) =>
        profileLoader(profile_id),
    },
  },
  mutateAndGetPayload: (
    { profileID: profile_id, unfollow },
    { followProfileLoader, unfollowProfileLoader }
  ) => {
    if (!followProfileLoader || !unfollowProfileLoader) {
      return new Error("You need to be signed in to perform this action")
    }

    let performAction
    if (unfollow) {
      performAction = unfollowProfileLoader(profile_id)
    } else {
      performAction = followProfileLoader({ profile_id })
    }

    return performAction.then(() => ({ profile_id }))
  },
})
