import { GraphQLString, GraphQLBoolean } from "graphql"
import { mutationWithClientMutationId } from "graphql-relay"
import { ArtworkType } from "schema/v2/artwork/index"
import { ResolverContext } from "types/graphql"

export default mutationWithClientMutationId<any, any, ResolverContext>({
  name: "SaveArtwork",
  description:
    "Save (or remove) an artwork to (from) a users default collection.",
  inputFields: {
    artworkID: {
      type: GraphQLString,
    },
    remove: {
      type: GraphQLBoolean,
    },
  } /*
  FIXME: Generated by the snake_case to camelCase codemod.
         Either use this to fix inputs and/or remove this comment.
  {
    const {
      artworkID,
      ..._newFields
    } = newFields;
    const oldFields = {
      artworkID: artwork_id,
      ..._newFields
    };
  }
  */,
  outputFields: {
    artwork: {
      type: ArtworkType,
      resolve: ({ artwork_id }, _, { artworkLoader }) =>
        artworkLoader(artwork_id),
    },
  },
  mutateAndGetPayload: (
    { artworkID: artwork_id, remove },
    { userID, saveArtworkLoader, deleteSavedArtworkLoader }
  ) => {
    if (!deleteSavedArtworkLoader || !saveArtworkLoader) {
      return new Error("You need to be signed in to perform this action")
    }

    const loader = remove ? deleteSavedArtworkLoader : saveArtworkLoader
    return loader(artwork_id, { user_id: userID }).then(() => ({ artwork_id }))
  },
})
