import { CollectorProfileFields } from "./collector_profile"
import {
  GraphQLBoolean,
  GraphQLString,
  GraphQLList,
  GraphQLEnumType,
} from "graphql"
import { mutationWithClientMutationId } from "graphql-relay"
import { ResolverContext } from "types/graphql"

export const IntentsType = new GraphQLEnumType({
  name: "Intents",
  values: {
    BUY_ART_AND_DESIGN: {
      value: "buy art & design",
    },
    SELL_ART_AND_DESIGN: {
      value: "sell art & design",
    },
    RESEARCH_ART_PRICES: {
      value: "research art prices",
    },
    LEARN_ABOUT_ART: {
      value: "learn about art",
    },
    FIND_ART_EXHIBITS: {
      value: "find out about new exhibitions",
    },
    READ_ART_MARKET_NEWS: {
      value: "read art market news",
    },
  },
})

export default mutationWithClientMutationId<any, any, ResolverContext>({
  name: "UpdateCollectorProfile",
  description: "Updating a collector profile (loyalty applicant status).",
  inputFields: {
    loyaltyApplicant: {
      type: GraphQLBoolean,
    },
    professionalBuyer: {
      type: GraphQLBoolean,
    },
    selfReportedPurchases: {
      type: GraphQLString,
    },
    intents: {
      type: new GraphQLList(IntentsType),
    },
  } /*
  FIXME: Generated by the snake_case to camelCase codemod.
         Either use this to fix inputs and/or remove this comment.
  {
    const {
      loyaltyApplicant,
      professionalBuyer,
      selfReportedPurchases,
      ..._newFields
    } = newFields;
    const oldFields = {
      loyaltyApplicant: loyalty_applicant,
      professionalBuyer: professional_buyer,
      selfReportedPurchases: self_reported_purchases,
      ..._newFields
    };
  }
  */,
  outputFields: CollectorProfileFields,
  mutateAndGetPayload: (
    { loyaltyApplicant, professionalBuyer, selfReportedPurchases, ..._options },
    { updateCollectorProfileLoader }
  ) => {
    const options: any = {
      loyalty_applicant: loyaltyApplicant,
      professional_buyer: professionalBuyer,
      self_reported_purchases: selfReportedPurchases,
      ..._options,
    }
    if (!updateCollectorProfileLoader) {
      throw new Error(
        "Missing Update Collector Profile Loader. Check your access token."
      )
    }
    return updateCollectorProfileLoader(options)
  },
})
