/**
 * CSV data exported from https://docs.google.com/spreadsheets/d/1EicHOCyCozsPBkVOkQGTTUtEds7qQuacUAgLy-C2-Nk/edit#gid=0
 *
 * To update data:
 *   1) Open spreadsheet link above
 *   2) File > Export > CSV
 *   3) Copy CSV data and paste into https://www.csvjson.com/csv2json
 *   4) Copy results and overwrite below
 */
export const staticCSVToJSONData = [
  {
    url: "/artist/alex-katz",
    slug: "alex-katz",
    name: "Alex Katz",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "3,540",
    "ROUNDED views to content from that artist (last month)": "3,500",
    "unique visitors to content from artist (last month)": "1,207",
    "ROUNDED unique visitors to content from artist (last month)": "1,200",
    "STR (last 12 months)": "79%",
    "Realized / estimate": "177%",
    "Highest realized price": "$4.17M",
  },
  {
    url: "/artist/alex-katz",
    slug: "alex-katz",
    name: "Alex Katz",
    "Artwork URL": "https://www.artsy.net/artwork/alex-katz-laura-1-49",
    "Artwork ids (recently sold) (comma separated)": "5aa2e90d7622dd49dc8b356c",
    "Realized Price (in dollars)": "$7,500",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/alex-katz",
    slug: "alex-katz",
    name: "Alex Katz",
    "Artwork URL":
      "https://www.artsy.net/artwork/alex-katz-luna-park-2-maravell-67-schroder-68",
    "Artwork ids (recently sold) (comma separated)": "5d9ca6fe8f1aee0011475cf7",
    "Realized Price (in dollars)": "$5,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/alex-katz",
    slug: "alex-katz",
    name: "Alex Katz",
    "Artwork URL": "https://www.artsy.net/artwork/alex-katz-rose-bud-30",
    "Artwork ids (recently sold) (comma separated)": "5d126f9bba46ba0012c3134f",
    "Realized Price (in dollars)": "$8,500",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/alex-katz",
    slug: "alex-katz",
    name: "Alex Katz",
    "Artwork URL":
      "https://www.artsy.net/artwork/alex-katz-fog-and-night-from-the-northern-landscapes-series",
    "Artwork ids (recently sold) (comma separated)": "5cffddff404918000ec89beb",
    "Realized Price (in dollars)": "$1,300",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/banksy",
    slug: "banksy",
    name: "Banksy",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "16,159",
    "ROUNDED views to content from that artist (last month)": "16,000",
    "unique visitors to content from artist (last month)": "5,610",
    "ROUNDED unique visitors to content from artist (last month)": "5,600",
    "STR (last 12 months)": "95%",
    "Realized / estimate": "184%",
    "Highest realized price": "12.16M",
  },
  {
    url: "/artist/banksy",
    slug: "banksy",
    name: "Banksy",
    "Artwork URL": "https://www.artsy.net/artwork/banksy-i-fought-the-law-74",
    "Artwork ids (recently sold) (comma separated)": "5e3854df108c9200113cd354",
    "Realized Price (in dollars)": "$41,595",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/banksy",
    slug: "banksy",
    name: "Banksy",
    "Artwork URL": "https://www.artsy.net/artwork/banksy-very-little-helps-81",
    "Artwork ids (recently sold) (comma separated)": "5e3854d523363e000f352f7f",
    "Realized Price (in dollars)": "$36,395",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/banksy",
    slug: "banksy",
    name: "Banksy",
    "Artwork URL": "https://www.artsy.net/artwork/banksy-monkey-parliament-24",
    "Artwork ids (recently sold) (comma separated)": "5e3854cf20273e00122131a5",
    "Realized Price (in dollars)": "$4,549",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/banksy",
    slug: "banksy",
    name: "Banksy",
    "Artwork URL":
      "https://www.artsy.net/artwork/banksy-because-im-worthless-red-2",
    "Artwork ids (recently sold) (comma separated)": "5e3854ce662102000e73328f",
    "Realized Price (in dollars)": "$20,797",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/banksy",
    slug: "banksy",
    name: "Banksy",
    "Artwork URL": "https://www.artsy.net/artwork/banksy-think-tank-20",
    "Artwork ids (recently sold) (comma separated)": "59d6a884c9dc240f49917380",
    "Realized Price (in dollars)": "$1,850",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/banksy",
    slug: "banksy",
    name: "Banksy",
    "Artwork URL": "https://www.artsy.net/artwork/banksy-soup-cans-34",
    "Artwork ids (recently sold) (comma separated)": "5de86d009a893d001244f5fe",
    "Realized Price (in dollars)": "$2,500",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/banksy",
    slug: "banksy",
    name: "Banksy",
    "Artwork URL": "https://www.artsy.net/artwork/banksy-peckham-rock-2",
    "Artwork ids (recently sold) (comma separated)": "5dcdc5a4f78568000ede76dc",
    "Realized Price (in dollars)": "$325",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/damien-hirst",
    slug: "damien-hirst",
    name: "Damien Hirst",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "5,848",
    "ROUNDED views to content from that artist (last month)": "5,800",
    "unique visitors to content from artist (last month)": "2,234",
    "ROUNDED unique visitors to content from artist (last month)": "2,200",
    "STR (last 12 months)": "84%",
    "Realized / estimate": "223%",
    "Highest realized price": "18.49M",
  },
  {
    url: "/artist/damien-hirst",
    slug: "damien-hirst",
    name: "Damien Hirst",
    "Artwork URL": "https://www.artsy.net/artwork/damien-hirst-lanatoside-b-17",
    "Artwork ids (recently sold) (comma separated)": "5e14aec8dfbde20011db500d",
    "Realized Price (in dollars)": "$15,752",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/damien-hirst",
    slug: "damien-hirst",
    name: "Damien Hirst",
    "Artwork URL": "https://www.artsy.net/artwork/damien-hirst-cafe-royal-4",
    "Artwork ids (recently sold) (comma separated)": "5e14aef3b54523000d05762f",
    "Realized Price (in dollars)": "$7,219",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/damien-hirst",
    slug: "damien-hirst",
    name: "Damien Hirst",
    "Artwork URL":
      "https://www.artsy.net/artwork/damien-hirst-mickey-blue-glitter-22",
    "Artwork ids (recently sold) (comma separated)": "5e14aee165cf5600126f8294",
    "Realized Price (in dollars)": "$31,504",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/damien-hirst",
    slug: "damien-hirst",
    name: "Damien Hirst",
    "Artwork URL":
      "https://www.artsy.net/artwork/damien-hirst-the-souls-on-jacobs-ladder-take-their-flight-unique-4",
    "Artwork ids (recently sold) (comma separated)": "5e14aed50229c0000e98c6cd",
    "Realized Price (in dollars)": "$19,690",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/damien-hirst",
    slug: "damien-hirst",
    name: "Damien Hirst",
    "Artwork URL": "https://www.artsy.net/artwork/damien-hirst-lanatoside-b-15",
    "Artwork ids (recently sold) (comma separated)": "5dd70d7e8a9348000d8f27e6",
    "Realized Price (in dollars)": "$11,106",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/damien-hirst",
    slug: "damien-hirst",
    name: "Damien Hirst",
    "Artwork URL": "https://www.artsy.net/artwork/damien-hirst-sceptic-8",
    "Artwork ids (recently sold) (comma separated)": "5d1239da8eae23000e02b902",
    "Realized Price (in dollars)": "$11,856",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/david-hockney",
    slug: "david-hockney",
    name: "David Hockney",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "4,965",
    "ROUNDED views to content from that artist (last month)": "4,900",
    "unique visitors to content from artist (last month)": "2,152",
    "ROUNDED unique visitors to content from artist (last month)": "2,100",
    "STR (last 12 months)": "93%",
    "Realized / estimate": "172%",
    "Highest realized price": "90.31M",
  },
  {
    url: "/artist/david-hockney",
    slug: "david-hockney",
    name: "David Hockney",
    "Artwork URL":
      "https://www.artsy.net/artwork/david-hockney-untitled-for-joe-wachs-1",
    "Artwork ids (recently sold) (comma separated)": "5e4c236733fef60011f0f3d7",
    "Realized Price (in dollars)": "$7,035",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/david-hockney",
    slug: "david-hockney",
    name: "David Hockney",
    "Artwork URL":
      "https://www.artsy.net/artwork/david-hockney-untitled-no-516-from-a-bigger-book-art-edition-d-3",
    "Artwork ids (recently sold) (comma separated)": "5e136924ed6a7a000e7de1e7",
    "Realized Price (in dollars)": "$10,410",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/david-hockney",
    slug: "david-hockney",
    name: "David Hockney",
    "Artwork URL":
      "https://www.artsy.net/artwork/david-hockney-a-bigger-book-art-edition-c-2",
    "Artwork ids (recently sold) (comma separated)": "5ddc31f1aab368000eda945d",
    "Realized Price (in dollars)": "$15,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/david-hockney",
    slug: "david-hockney",
    name: "David Hockney",
    "Artwork URL":
      "https://www.artsy.net/artwork/david-hockney-the-student-homage-to-picasso-18",
    "Artwork ids (recently sold) (comma separated)": "5dd70d75fa0f8a000efa26a5",
    "Realized Price (in dollars)": "$10,096",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/david-hockney",
    slug: "david-hockney",
    name: "David Hockney",
    "Artwork URL": "https://www.artsy.net/artwork/david-hockney-five-candles-5",
    "Artwork ids (recently sold) (comma separated)": "5dbb40930044a73741abf780",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/david-hockney",
    slug: "david-hockney",
    name: "David Hockney",
    "Artwork URL":
      "https://www.artsy.net/artwork/david-hockney-the-studio-number-45",
    "Artwork ids (recently sold) (comma separated)": "5d9b92450a36a6000e0d3c99",
    "Realized Price (in dollars)": "$11,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/david-shrigley",
    slug: "david-shrigley",
    name: "David Shrigley",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "2,562",
    "ROUNDED views to content from that artist (last month)": "2,500",
    "unique visitors to content from artist (last month)": 804,
    "ROUNDED unique visitors to content from artist (last month)": 800,
    "STR (last 12 months)": "82%",
    "Realized / estimate": "163%",
    "Highest realized price": "13.30K",
  },
  {
    url: "/artist/david-shrigley",
    slug: "david-shrigley",
    name: "David Shrigley",
    "Artwork URL":
      "https://www.artsy.net/artwork/david-shrigley-i-love-dot-dot-dot-6",
    "Artwork ids (recently sold) (comma separated)": "5e42c58aabfaa0000f599b39",
    "Realized Price (in dollars)": "$1,929",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/david-shrigley",
    slug: "david-shrigley",
    name: "David Shrigley",
    "Artwork URL":
      "https://www.artsy.net/artwork/david-shrigley-i-love-dot-dot-dot-4",
    "Artwork ids (recently sold) (comma separated)": "5e3854db64aca0000ed1c52e",
    "Realized Price (in dollars)": "$1,559",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/david-shrigley",
    slug: "david-shrigley",
    name: "David Shrigley",
    "Artwork URL":
      "https://www.artsy.net/artwork/david-shrigley-right-ear-made-from-bronze",
    "Artwork ids (recently sold) (comma separated)": "5e3854d3d0cec9000e8c0705",
    "Realized Price (in dollars)": "$1,039",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/david-shrigley",
    slug: "david-shrigley",
    name: "David Shrigley",
    "Artwork URL": "https://www.artsy.net/artwork/david-shrigley-kindness-16",
    "Artwork ids (recently sold) (comma separated)": "5e3854d155666d000e3c9fec",
    "Realized Price (in dollars)": "$1,559",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/david-shrigley",
    slug: "david-shrigley",
    name: "David Shrigley",
    "Artwork URL":
      "https://www.artsy.net/artwork/david-shrigley-fucking-ace-56",
    "Artwork ids (recently sold) (comma separated)": "5dd557edddd6140012f9f99b",
    "Realized Price (in dollars)": "$1,839",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/david-shrigley",
    slug: "david-shrigley",
    name: "David Shrigley",
    "Artwork URL":
      "https://www.artsy.net/artwork/david-shrigley-i-endorse-everything-1",
    "Artwork ids (recently sold) (comma separated)": "5dca90691168373d76ef25bd",
    "Realized Price (in dollars)": "$1,223",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/david-shrigley",
    slug: "david-shrigley",
    name: "David Shrigley",
    "Artwork URL":
      "https://www.artsy.net/artwork/david-shrigley-fucking-ace-55",
    "Artwork ids (recently sold) (comma separated)": "5dc445a3464aed0012de5201",
    "Realized Price (in dollars)": "$1,291",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/david-shrigley",
    slug: "david-shrigley",
    name: "David Shrigley",
    "Artwork URL":
      "https://www.artsy.net/artwork/david-shrigley-its-all-your-fault-5",
    "Artwork ids (recently sold) (comma separated)": "5dc445a2fa952600119f15b0",
    "Realized Price (in dollars)": "$1,227",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/ed-ruscha",
    slug: "ed-ruscha",
    name: "Ed Ruscha",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "2,402",
    "ROUNDED views to content from that artist (last month)": "2,400",
    "unique visitors to content from artist (last month)": 962,
    "ROUNDED unique visitors to content from artist (last month)": 960,
    "STR (last 12 months)": "89%",
    "Realized / estimate": "153%",
    "Highest realized price": "52.48M",
  },
  {
    url: "/artist/ed-ruscha",
    slug: "ed-ruscha",
    name: "Ed Ruscha",
    "Artwork URL":
      "https://www.artsy.net/artwork/ed-ruscha-a-particular-kind-of-heaven-3",
    "Artwork ids (recently sold) (comma separated)": "5e3854d7de3c4e000e45266c",
    "Realized Price (in dollars)": "$1,429",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/ed-ruscha",
    slug: "ed-ruscha",
    name: "Ed Ruscha",
    "Artwork URL":
      "https://www.artsy.net/artwork/ed-ruscha-says-i-to-myself-number-1",
    "Artwork ids (recently sold) (comma separated)": "5dbb3ae24ead1100113eca64",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/ed-ruscha",
    slug: "ed-ruscha",
    name: "Ed Ruscha",
    "Artwork URL": "https://www.artsy.net/artwork/ed-ruscha-golden-gardens",
    "Artwork ids (recently sold) (comma separated)": "5da5e0f7da412100142f7773",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/ed-ruscha",
    slug: "ed-ruscha",
    name: "Ed Ruscha",
    "Artwork URL": "https://www.artsy.net/artwork/ed-ruscha-step-downs",
    "Artwork ids (recently sold) (comma separated)": "5cd58c3677ca621a43f80bfe",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/ed-ruscha",
    slug: "ed-ruscha",
    name: "Ed Ruscha",
    "Artwork URL": "https://www.artsy.net/artwork/ed-ruscha-question",
    "Artwork ids (recently sold) (comma separated)": "5ccb07cd456ec36e502793de",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/ed-ruscha",
    slug: "ed-ruscha",
    name: "Ed Ruscha",
    "Artwork URL": "https://www.artsy.net/artwork/ed-ruscha-taxi-cab-9",
    "Artwork ids (recently sold) (comma separated)": "5a9cb92bc9dc24735a405e7b",
    "Realized Price (in dollars)": "$1,250",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/eddie-martinez",
    slug: "eddie-martinez",
    name: "Eddie Martinez",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "2,212",
    "ROUNDED views to content from that artist (last month)": "2,200",
    "unique visitors to content from artist (last month)": 784,
    "ROUNDED unique visitors to content from artist (last month)": 780,
    "STR (last 12 months)": "100%",
    "Realized / estimate": "366%",
    "Highest realized price": "2.01M",
  },
  {
    url: "/artist/eddie-martinez",
    slug: "eddie-martinez",
    name: "Eddie Martinez",
    "Artwork URL":
      "https://www.artsy.net/artwork/eddie-martinez-love-letter-number-4-decade-young",
    "Artwork ids (recently sold) (comma separated)": "5db9bab648eea3000e098182",
    "Realized Price (in dollars)": "$240,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/eddie-martinez",
    slug: "eddie-martinez",
    name: "Eddie Martinez",
    "Artwork URL": "https://www.artsy.net/artwork/eddie-martinez-untitled-256",
    "Artwork ids (recently sold) (comma separated)": "5d8cfc0100498f001109c5b2",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/eddie-martinez",
    slug: "eddie-martinez",
    name: "Eddie Martinez",
    "Artwork URL": "https://www.artsy.net/artwork/eddie-martinez-untitled-255",
    "Artwork ids (recently sold) (comma separated)": "5d8cfc006d608e000eb2df7c",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/eddie-martinez",
    slug: "eddie-martinez",
    name: "Eddie Martinez",
    "Artwork URL": "https://www.artsy.net/artwork/eddie-martinez-untitled-245",
    "Artwork ids (recently sold) (comma separated)": "5d13eb67b36211000fb646e9",
    "Realized Price (in dollars)": "$8,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/eddie-martinez",
    slug: "eddie-martinez",
    name: "Eddie Martinez",
    "Artwork URL":
      "https://www.artsy.net/artwork/eddie-martinez-fine-ants-black-out-1",
    "Artwork ids (recently sold) (comma separated)": "5caf386a6eb7464d4c0a8696",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/eddie-martinez",
    slug: "eddie-martinez",
    name: "Eddie Martinez",
    "Artwork URL":
      "https://www.artsy.net/artwork/eddie-martinez-study-for-fine-arts",
    "Artwork ids (recently sold) (comma separated)": "5abc08a11a1e8613b5594ce2",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/eddie-martinez",
    slug: "eddie-martinez",
    name: "Eddie Martinez",
    "Artwork URL":
      "https://www.artsy.net/artwork/eddie-martinez-united-states-1",
    "Artwork ids (recently sold) (comma separated)": "5a9035cd275b24121f190954",
    "Realized Price (in dollars)": "$4,500",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/eddie-martinez",
    slug: "eddie-martinez",
    name: "Eddie Martinez",
    "Artwork URL":
      "https://www.artsy.net/artwork/eddie-martinez-small-mandala-black-number-2",
    "Artwork ids (recently sold) (comma separated)": "5a8f50c4275b241a68bad8b7",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/genieve-figgis",
    slug: "",
    name: "Genieve Figgis",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "2,678",
    "ROUNDED views to content from that artist (last month)": "2,600",
    "unique visitors to content from artist (last month)": 893,
    "ROUNDED unique visitors to content from artist (last month)": 890,
    "STR (last 12 months)": "100%",
    "Realized / estimate": "579%",
    "Highest realized price": "303.49K",
  },
  {
    url: "/artist/harland-miller",
    slug: "harland-miller",
    name: "Harland Miller",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "2,394",
    "ROUNDED views to content from that artist (last month)": "2,400",
    "unique visitors to content from artist (last month)": 684,
    "ROUNDED unique visitors to content from artist (last month)": 680,
    "STR (last 12 months)": "85%",
    "Realized / estimate": "296%",
    "Highest realized price": "315.57M",
  },
  {
    url: "/artist/harland-miller",
    slug: "harland-miller",
    name: "Harland Miller",
    "Artwork URL":
      "https://www.artsy.net/artwork/harland-miller-i-am-the-one-ive-been-waiting-for-30",
    "Artwork ids (recently sold) (comma separated)": "5dca905ce3a4d9578eea39d3",
    "Realized Price (in dollars)": "$34,781",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/harland-miller",
    slug: "harland-miller",
    name: "Harland Miller",
    "Artwork URL":
      "https://www.artsy.net/artwork/harland-miller-in-shadows-i-boogie-blue-1",
    "Artwork ids (recently sold) (comma separated)": "5d9dfcad13793a000e6c3a66",
    "Realized Price (in dollars)": "$4,900",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/harland-miller",
    slug: "harland-miller",
    name: "Harland Miller",
    "Artwork URL":
      "https://www.artsy.net/artwork/harland-miller-fuck-art-lets-dance-slash-fuck-dancing-lets-fuck-deck-chairs",
    "Artwork ids (recently sold) (comma separated)": "5d0b49c914c9e9000eaa3523",
    "Realized Price (in dollars)": "$5,301",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/harland-miller",
    slug: "harland-miller",
    name: "Harland Miller",
    "Artwork URL":
      "https://www.artsy.net/artwork/harland-miller-fuck-art-lets-dance-5",
    "Artwork ids (recently sold) (comma separated)": "5beddd9d33eff84d618d4287",
    "Realized Price (in dollars)": "$35,774",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/harland-miller",
    slug: "harland-miller",
    name: "Harland Miller",
    "Artwork URL":
      "https://www.artsy.net/artwork/harland-miller-death-whats-in-it-for-me-6",
    "Artwork ids (recently sold) (comma separated)": "5aa7b7b81a1e861356fd6bd0",
    "Realized Price (in dollars)": "$19,444",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/harland-miller",
    slug: "harland-miller",
    name: "Harland Miller",
    "Artwork URL":
      "https://www.artsy.net/artwork/harland-miller-the-me-i-never-knew-12",
    "Artwork ids (recently sold) (comma separated)": "5a9035ef9c18db5309bcf8c8",
    "Realized Price (in dollars)": "$8,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/harland-miller",
    slug: "harland-miller",
    name: "Harland Miller",
    "Artwork URL":
      "https://www.artsy.net/artwork/harland-miller-death-whats-in-it-for-me-1",
    "Artwork ids (recently sold) (comma separated)": "58d17c59cd530e4ca80bf432",
    "Realized Price (in dollars)": "$10,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/invader",
    slug: "invader",
    name: "Invader",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "1,923",
    "ROUNDED views to content from that artist (last month)": "1,900",
    "unique visitors to content from artist (last month)": 652,
    "ROUNDED unique visitors to content from artist (last month)": 650,
    "STR (last 12 months)": "100%",
    "Realized / estimate": "253%",
    "Highest realized price": "1.22M",
  },
  {
    url: "/artist/invader",
    slug: "invader",
    name: "Invader",
    "Artwork URL": "https://www.artsy.net/artwork/invader-invaded-hypnosis-1",
    "Artwork ids (recently sold) (comma separated)": "5e3854d1578545000d90700e",
    "Realized Price (in dollars)": "$9,748",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/invader",
    slug: "invader",
    name: "Invader",
    "Artwork URL":
      "https://www.artsy.net/artwork/invader-oh-dot-dot-dot-alright-5",
    "Artwork ids (recently sold) (comma separated)": "5e3854cedea61c000e0a7268",
    "Realized Price (in dollars)": "$11,698",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/invader",
    slug: "invader",
    name: "Invader",
    "Artwork URL": "https://www.artsy.net/artwork/invader-warning-invader-1",
    "Artwork ids (recently sold) (comma separated)": "5e3854ccc7b44f000d1c3fb1",
    "Realized Price (in dollars)": "$6,499",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/invader",
    slug: "invader",
    name: "Invader",
    "Artwork URL": "https://www.artsy.net/artwork/invader-invaded-scream-6",
    "Artwork ids (recently sold) (comma separated)": "5e3854cca7925d00115cb942",
    "Realized Price (in dollars)": "$11,048",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/invader",
    slug: "invader",
    name: "Invader",
    "Artwork URL":
      "https://www.artsy.net/artwork/invader-invasion-kit-number-11-blue-2",
    "Artwork ids (recently sold) (comma separated)": "5e3854ca2595c60012fd0f05",
    "Realized Price (in dollars)": "$7,194",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/invader",
    slug: "invader",
    name: "Invader",
    "Artwork URL": "https://www.artsy.net/artwork/invader-led-32",
    "Artwork ids (recently sold) (comma separated)": "5e136bdac2bd6a00114dc19f",
    "Realized Price (in dollars)": "$4,424",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/katherine-bernhardt",
    slug: "katherine-bernhardt",
    name: "Katherine Bernhardt",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "2,696",
    "ROUNDED views to content from that artist (last month)": "2,700",
    "unique visitors to content from artist (last month)": 758,
    "ROUNDED unique visitors to content from artist (last month)": 750,
    "STR (last 12 months)": "95%",
    "Realized / estimate": "246%",
    "Highest realized price": "81.25K",
  },
  {
    url: "/artist/katherine-bernhardt",
    slug: "katherine-bernhardt",
    name: "Katherine Bernhardt",
    "Artwork URL":
      "https://www.artsy.net/artwork/katherine-bernhardt-untitled-106",
    "Artwork ids (recently sold) (comma separated)": "5cc8d5559cdd801f789e5fec",
    "Realized Price (in dollars)": "$13,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/katherine-bernhardt",
    slug: "katherine-bernhardt",
    name: "Katherine Bernhardt",
    "Artwork URL":
      "https://www.artsy.net/artwork/katherine-bernhardt-cigarette-1",
    "Artwork ids (recently sold) (comma separated)": "5ddd851ae67c730012666296",
    "Realized Price (in dollars)": "$12,559",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/katherine-bernhardt",
    slug: "katherine-bernhardt",
    name: "Katherine Bernhardt",
    "Artwork URL": "https://www.artsy.net/artwork/katherine-bernhardt-time",
    "Artwork ids (recently sold) (comma separated)": "5dc2afa3fa9526000de25e61",
    "Realized Price (in dollars)": "$1,808",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/katherine-bernhardt",
    slug: "katherine-bernhardt",
    name: "Katherine Bernhardt",
    "Artwork URL":
      "https://www.artsy.net/artwork/katherine-bernhardt-untitled-147",
    "Artwork ids (recently sold) (comma separated)": "5dbb3ae26a65d700114f410d",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/katherine-bernhardt",
    slug: "katherine-bernhardt",
    name: "Katherine Bernhardt",
    "Artwork URL":
      "https://www.artsy.net/artwork/katherine-bernhardt-watermill",
    "Artwork ids (recently sold) (comma separated)": "5d23906a815375000e83ae7a",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/katherine-bernhardt",
    slug: "katherine-bernhardt",
    name: "Katherine Bernhardt",
    "Artwork URL":
      "https://www.artsy.net/artwork/katherine-bernhardt-free-throw",
    "Artwork ids (recently sold) (comma separated)": "5ce2e995eeaae6000e648798",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/katherine-bernhardt",
    slug: "katherine-bernhardt",
    name: "Katherine Bernhardt",
    "Artwork URL":
      "https://www.artsy.net/artwork/katherine-bernhardt-sea-turtles-1",
    "Artwork ids (recently sold) (comma separated)": "5ca769f5546ddc659a908f66",
    "Realized Price (in dollars)": "$3,800",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/kaws",
    slug: "kaws",
    name: "KAWS",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "9,689",
    "ROUNDED views to content from that artist (last month)": "9,700",
    "unique visitors to content from artist (last month)": "4,460",
    "ROUNDED unique visitors to content from artist (last month)": "4,400",
    "STR (last 12 months)": "92%",
    "Realized / estimate": "234%",
    "Highest realized price": "14.77M",
  },
  {
    url: "/artist/kaws",
    slug: "kaws",
    name: "KAWS",
    "Artwork URL":
      "https://www.artsy.net/artwork/kaws-clean-slate-set-of-three-2",
    "Artwork ids (recently sold) (comma separated)": "5e3c3b928d0205001257993f",
    "Realized Price (in dollars)": "$1,900",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/kaws",
    slug: "kaws",
    name: "KAWS",
    "Artwork URL": "https://www.artsy.net/artwork/kaws-companion-vs-pikachu",
    "Artwork ids (recently sold) (comma separated)": "5e3854cbde3c4e0012b77086",
    "Realized Price (in dollars)": "$15,897",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/kaws",
    slug: "kaws",
    name: "KAWS",
    "Artwork URL":
      "https://www.artsy.net/artwork/kaws-4-foot-dissected-comapnion-black",
    "Artwork ids (recently sold) (comma separated)": "5e13a54ac2bd6a000dd0fd11",
    "Realized Price (in dollars)": "$75,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/kaws",
    slug: "kaws",
    name: "KAWS",
    "Artwork URL": "https://www.artsy.net/artwork/kaws-gone-grey",
    "Artwork ids (recently sold) (comma separated)": "5e13a501f29651001241f5e9",
    "Realized Price (in dollars)": "$1,300",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/kaws",
    slug: "kaws",
    name: "KAWS",
    "Artwork URL": "https://www.artsy.net/artwork/kaws-pinocchio-19",
    "Artwork ids (recently sold) (comma separated)": "5ddc320315981e001357d395",
    "Realized Price (in dollars)": "$85,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/kaws",
    slug: "kaws",
    name: "KAWS",
    "Artwork URL": "https://www.artsy.net/artwork/kaws-untitled-653",
    "Artwork ids (recently sold) (comma separated)": "58f010d9b202a373775d2e74",
    "Realized Price (in dollars)": "$2,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/kehinde-wiley",
    slug: "kehinde-wiley",
    name: "Kehinde Wiley",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "6,717",
    "ROUNDED views to content from that artist (last month)": "6,700",
    "unique visitors to content from artist (last month)": "3,163",
    "ROUNDED unique visitors to content from artist (last month)": "3,100",
    "STR (last 12 months)": "80%",
    "Realized / estimate": "166%",
    "Highest realized price": "$300K",
  },
  {
    url: "/artist/kehinde-wiley",
    slug: "kehinde-wiley",
    name: "Kehinde Wiley",
    "Artwork URL":
      "https://www.artsy.net/artwork/kehinde-wiley-passing-slash-posing-number-1",
    "Artwork ids (recently sold) (comma separated)": "5ae969be139b217e8eb41b5d",
    "Realized Price (in dollars)": "$85,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/kehinde-wiley",
    slug: "kehinde-wiley",
    name: "Kehinde Wiley",
    "Artwork URL":
      "https://www.artsy.net/artwork/kehinde-wiley-st-francis-of-adelaide-1",
    "Artwork ids (recently sold) (comma separated)": "5c9935f5d5b39c464895965c",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/kehinde-wiley",
    slug: "kehinde-wiley",
    name: "Kehinde Wiley",
    "Artwork URL":
      "https://www.artsy.net/artwork/kehinde-wiley-andries-stilte-100-percent-cotton-beach-towel",
    "Artwork ids (recently sold) (comma separated)": "5ab0e0c2a09a675b2792b5d9",
    "Realized Price (in dollars)": "$460",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/kehinde-wiley",
    slug: "kehinde-wiley",
    name: "Kehinde Wiley",
    "Artwork URL":
      "https://www.artsy.net/artwork/kehinde-wiley-limbo-series-number-5",
    "Artwork ids (recently sold) (comma separated)": "5a53f4018b3b817721919e43",
    "Realized Price (in dollars)": "$14,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/kehinde-wiley",
    slug: "kehinde-wiley",
    name: "Kehinde Wiley",
    "Artwork URL":
      "https://www.artsy.net/artwork/kehinde-wiley-after-la-negresse-1872-1",
    "Artwork ids (recently sold) (comma separated)": "564d5c1caa00b563c90003b0",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/kehinde-wiley",
    slug: "kehinde-wiley",
    name: "Kehinde Wiley",
    "Artwork URL": "https://www.artsy.net/artwork/kehinde-wiley-plate-set",
    "Artwork ids (recently sold) (comma separated)": "551473217261691b72431b00",
    "Realized Price (in dollars)": "$525",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/kehinde-wiley",
    slug: "kehinde-wiley",
    name: "Kehinde Wiley",
    "Artwork URL":
      "https://www.artsy.net/artwork/kehinde-wiley-untitled-jamaica-study",
    "Artwork ids (recently sold) (comma separated)": "533eec0da09a67f438000024",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/mr-brainwash",
    slug: "mr-brainwash",
    name: "Mr. Brainwash",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "5,152",
    "ROUNDED views to content from that artist (last month)": "5,100",
    "unique visitors to content from artist (last month)": "1,577",
    "ROUNDED unique visitors to content from artist (last month)": "1,500",
    "STR (last 12 months)": "100%",
    "Realized / estimate": "149%",
    "Highest realized price": "122.50K",
  },
  {
    url: "/artist/mr-brainwash",
    slug: "mr-brainwash",
    name: "Mr. Brainwash",
    "Artwork URL":
      "https://www.artsy.net/artwork/mr-brainwash-happy-b-day-madonna-2",
    "Artwork ids (recently sold) (comma separated)": "5e3854ccfacf84000d1bf2cc",
    "Realized Price (in dollars)": "$1,939",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/mr-brainwash",
    slug: "mr-brainwash",
    name: "Mr. Brainwash",
    "Artwork URL":
      "https://www.artsy.net/artwork/mr-brainwash-samo-is-alive-12",
    "Artwork ids (recently sold) (comma separated)": "5de5778c8dcc5300112cffaa",
    "Realized Price (in dollars)": "$1,003",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/mr-brainwash",
    slug: "mr-brainwash",
    name: "Mr. Brainwash",
    "Artwork URL": "https://www.artsy.net/artwork/mr-brainwash-love-on-6",
    "Artwork ids (recently sold) (comma separated)": "5dbb5c0d6a65d7000ea864f4",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/mr-brainwash",
    slug: "mr-brainwash",
    name: "Mr. Brainwash",
    "Artwork URL": "https://www.artsy.net/artwork/mr-brainwash-rescue",
    "Artwork ids (recently sold) (comma separated)": "5d28b705aa496a000e427f71",
    "Realized Price (in dollars)": "$1,650",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/mr-brainwash",
    slug: "mr-brainwash",
    name: "Mr. Brainwash",
    "Artwork URL":
      "https://www.artsy.net/artwork/mr-brainwash-life-is-beautiful-black-6",
    "Artwork ids (recently sold) (comma separated)": "5a7499a8a09a675e26f4fd30",
    "Realized Price (in dollars)": "$1,800",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/nina-chanel-abney",
    slug: "nina-chanel-abney",
    name: "Nina Chanel Abney",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "1,393",
    "ROUNDED views to content from that artist (last month)": "1,300",
    "unique visitors to content from artist (last month)": 473,
    "ROUNDED unique visitors to content from artist (last month)": 470,
    "STR (last 12 months)": "100%",
    "Realized / estimate": "222%",
    "Highest realized price": "285.64K",
  },
  {
    url: "/artist/nina-chanel-abney",
    slug: "nina-chanel-abney",
    name: "Nina Chanel Abney",
    "Artwork URL": "https://www.artsy.net/artwork/nina-chanel-abney-untitled-7",
    "Artwork ids (recently sold) (comma separated)": "5abd5bf98b3b81795ad62f04",
    "Realized Price (in dollars)": "$15,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/nina-chanel-abney",
    slug: "nina-chanel-abney",
    name: "Nina Chanel Abney",
    "Artwork URL":
      "https://www.artsy.net/artwork/nina-chanel-abney-huf-skateboard-deck",
    "Artwork ids (recently sold) (comma separated)": "5d8a372516bd45000e2b7618",
    "Realized Price (in dollars)": "$488",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)":
      "5d680e1798cff6000e433dfb",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/nina-chanel-abney",
    slug: "nina-chanel-abney",
    name: "Nina Chanel Abney",
    "Artwork URL":
      "https://www.artsy.net/artwork/nina-chanel-abney-untitled-10",
    "Artwork ids (recently sold) (comma separated)": "5bc3bbffc9b87154a081eb3d",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/nina-chanel-abney",
    slug: "nina-chanel-abney",
    name: "Nina Chanel Abney",
    "Artwork URL":
      "https://www.artsy.net/artwork/nina-chanel-abney-untitled-6k",
    "Artwork ids (recently sold) (comma separated)": "587935d7cd530e085e000317",
    "Realized Price (in dollars)": "$6,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/roy-lichtenstein",
    slug: "roy-lichtenstein",
    name: "Roy Lichtenstein",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "4,642",
    "ROUNDED views to content from that artist (last month)": "4,600",
    "unique visitors to content from artist (last month)": "2,124",
    "ROUNDED unique visitors to content from artist (last month)": "2,100",
    "STR (last 12 months)": "89%",
    "Realized / estimate": "139%",
    "Highest realized price": "95.36M",
  },
  {
    url: "/artist/roy-lichtenstein",
    slug: "roy-lichtenstein",
    name: "Roy Lichtenstein",
    "Artwork URL":
      "https://www.artsy.net/artwork/roy-lichtenstein-shipboard-girl-64",
    "Artwork ids (recently sold) (comma separated)": "5da61f13e22573000ef129ff",
    "Realized Price (in dollars)": "$42,500",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/roy-lichtenstein",
    slug: "roy-lichtenstein",
    name: "Roy Lichtenstein",
    "Artwork URL":
      "https://www.artsy.net/artwork/roy-lichtenstein-as-i-opened-fire-triptych-26",
    "Artwork ids (recently sold) (comma separated)": "58e6fa987622dd03e0f93ec6",
    "Realized Price (in dollars)": "$2,250",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/roy-lichtenstein",
    slug: "roy-lichtenstein",
    name: "Roy Lichtenstein",
    "Artwork URL":
      "https://www.artsy.net/artwork/roy-lichtenstein-crying-girl-2020",
    "Artwork ids (recently sold) (comma separated)": "5e4304d173c1200013b5347d",
    "Realized Price (in dollars)": "$2,400",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/roy-lichtenstein",
    slug: "roy-lichtenstein",
    name: "Roy Lichtenstein",
    "Artwork URL":
      "https://www.artsy.net/artwork/roy-lichtenstein-finger-pointing-10",
    "Artwork ids (recently sold) (comma separated)": "5dcc53b7330f35000e45defe",
    "Realized Price (in dollars)": "$11,593",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/roy-lichtenstein",
    slug: "roy-lichtenstein",
    name: "Roy Lichtenstein",
    "Artwork URL": "https://www.artsy.net/artwork/roy-lichtenstein-mirror-4",
    "Artwork ids (recently sold) (comma separated)": "5da61f187fa2f9001293ceb1",
    "Realized Price (in dollars)": "$5,500",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/roy-lichtenstein",
    slug: "roy-lichtenstein",
    name: "Roy Lichtenstein",
    "Artwork URL":
      "https://www.artsy.net/artwork/roy-lichtenstein-spray-can-1-cent-life",
    "Artwork ids (recently sold) (comma separated)": "59f79e609c18db1a05255f7a",
    "Realized Price (in dollars)": "$1,450",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/roy-lichtenstein",
    slug: "roy-lichtenstein",
    name: "Roy Lichtenstein",
    "Artwork URL": "https://www.artsy.net/artwork/roy-lichtenstein-whamm-1",
    "Artwork ids (recently sold) (comma separated)": "5de0047a5bedd6000e8dab7c",
    "Realized Price (in dollars)": "$2,491",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/sterling-ruby",
    slug: "sterling-ruby",
    name: "Sterling Ruby",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "1,488",
    "ROUNDED views to content from that artist (last month)": "1,400",
    "unique visitors to content from artist (last month)": 734,
    "ROUNDED unique visitors to content from artist (last month)": 730,
    "STR (last 12 months)": "84%",
    "Realized / estimate": "126%",
    "Highest realized price": "1.78M",
  },
  {
    url: "/artist/sterling-ruby",
    slug: "sterling-ruby",
    name: "Sterling Ruby",
    "Artwork URL":
      "https://www.artsy.net/artwork/sterling-ruby-anti-poster-i-and-ii-2-works",
    "Artwork ids (recently sold) (comma separated)": "5919e8eecb4c275e88525790",
    "Realized Price (in dollars)": "$2,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/sterling-ruby",
    slug: "sterling-ruby",
    name: "Sterling Ruby",
    "Artwork URL":
      "https://www.artsy.net/artwork/sterling-ruby-anti-print-poster",
    "Artwork ids (recently sold) (comma separated)": "5bfdfcc5ee01b40028ed3475",
    "Realized Price (in dollars)": "$1,500",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/sterling-ruby",
    slug: "sterling-ruby",
    name: "Sterling Ruby",
    "Artwork URL":
      "https://www.artsy.net/artwork/sterling-ruby-exhm-slash-iadt-2-3505",
    "Artwork ids (recently sold) (comma separated)": "56f990c6275b247bf8003440",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/sterling-ruby",
    slug: "sterling-ruby",
    name: "Sterling Ruby",
    "Artwork URL":
      "https://www.artsy.net/artwork/sterling-ruby-fallen-night-stalkers-memorial",
    "Artwork ids (recently sold) (comma separated)": "5d96344194b599001203e912",
    "Realized Price (in dollars)": "$2,200",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/sterling-ruby",
    slug: "sterling-ruby",
    name: "Sterling Ruby",
    "Artwork URL":
      "https://www.artsy.net/artwork/sterling-ruby-head-trekkers-weight-2",
    "Artwork ids (recently sold) (comma separated)": "58a336dc275b2472a95fa44b",
    "Realized Price (in dollars)": "$24,390",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/sterling-ruby",
    slug: "sterling-ruby",
    name: "Sterling Ruby",
    "Artwork URL":
      "https://www.artsy.net/artwork/sterling-ruby-physicalism-the-recombine",
    "Artwork ids (recently sold) (comma separated)": "5d13eb6c3a1b440012737c82",
    "Realized Price (in dollars)": "$6,500",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/sterling-ruby",
    slug: "sterling-ruby",
    name: "Sterling Ruby",
    "Artwork URL":
      "https://www.artsy.net/artwork/sterling-ruby-untitled-craft-geometry-study-number-3",
    "Artwork ids (recently sold) (comma separated)": "5d9634f4683a68000f116471",
    "Realized Price (in dollars)": "$2,600",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/stik",
    slug: "stik",
    name: "Stik",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "1,248",
    "ROUNDED views to content from that artist (last month)": "1,200",
    "unique visitors to content from artist (last month)": 395,
    "ROUNDED unique visitors to content from artist (last month)": 390,
    "STR (last 12 months)": "100%",
    "Realized / estimate": "211%",
    "Highest realized price": "250.03K",
  },
  {
    url: "/artist/stik",
    slug: "stik",
    name: "Stik",
    "Artwork URL": "https://www.artsy.net/artwork/stik-big-issue-series",
    "Artwork ids (recently sold) (comma separated)": "5e136c391a08d2000da0ed23",
    "Realized Price (in dollars)": "$4,944",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/stik",
    slug: "stik",
    name: "Stik",
    "Artwork URL": "https://www.artsy.net/artwork/stik-liberty-complete-set",
    "Artwork ids (recently sold) (comma separated)": "5e136bee9d1614000ed756a5",
    "Realized Price (in dollars)": "$1,561",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/stik",
    slug: "stik",
    name: "Stik",
    "Artwork URL":
      "https://www.artsy.net/artwork/stik-standing-figure-book-red-blue-yellow-orange-teal-and-grey-1",
    "Artwork ids (recently sold) (comma separated)": "5e3854c92595c60012fd0efb",
    "Realized Price (in dollars)": "$3,899",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/stik",
    slug: "stik",
    name: "Stik",
    "Artwork URL": "https://www.artsy.net/artwork/stik-standing-figure-red-23",
    "Artwork ids (recently sold) (comma separated)": "5d2e13f36cae2f000e39d3dc",
    "Realized Price (in dollars)": "$1,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/stik",
    slug: "stik",
    name: "Stik",
    "Artwork URL": "https://www.artsy.net/artwork/stik-standing-figure-red-24",
    "Artwork ids (recently sold) (comma separated)": "5dc4459d7671594b2e5016b6",
    "Realized Price (in dollars)": "$710",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/stik",
    slug: "stik",
    name: "Stik",
    "Artwork URL": "https://www.artsy.net/artwork/stik-wall-1",
    "Artwork ids (recently sold) (comma separated)": "5e3854e3de3c4e0012b770a1",
    "Realized Price (in dollars)": "$649",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/takashi-murakami",
    slug: "takashi-murakami",
    name: "Takashi Murakami",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "10,675",
    "ROUNDED views to content from that artist (last month)": "10,600",
    "unique visitors to content from artist (last month)": "4,623",
    "ROUNDED unique visitors to content from artist (last month)": "4,600",
    "STR (last 12 months)": "93%",
    "Realized / estimate": "183%",
    "Highest realized price": "15.16M",
  },
  {
    url: "/artist/takashi-murakami",
    slug: "takashi-murakami",
    name: "Takashi Murakami",
    "Artwork URL":
      "https://www.artsy.net/artwork/takashi-murakami-champagne-supernova-blue-9",
    "Artwork ids (recently sold) (comma separated)": "5e13a54eed6a7a000e7ded3a",
    "Realized Price (in dollars)": "$2,200",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/takashi-murakami",
    slug: "takashi-murakami",
    name: "Takashi Murakami",
    "Artwork URL":
      "https://www.artsy.net/artwork/takashi-murakami-enso-momento-mori-red-on-blue",
    "Artwork ids (recently sold) (comma separated)": "5e13a54f2f7707000d32e6dc",
    "Realized Price (in dollars)": "$1,100",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/takashi-murakami",
    slug: "takashi-murakami",
    name: "Takashi Murakami",
    "Artwork URL":
      "https://www.artsy.net/artwork/takashi-murakami-i-look-back-and-there-my-beautiful-memories-4",
    "Artwork ids (recently sold) (comma separated)": "5e3c3b91cb5ec9000e47c91f",
    "Realized Price (in dollars)": "$1,900",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/takashi-murakami",
    slug: "takashi-murakami",
    name: "Takashi Murakami",
    "Artwork URL": "https://www.artsy.net/artwork/takashi-murakami-mr-dob-48",
    "Artwork ids (recently sold) (comma separated)": "59e928c3275b2424b960b8c9",
    "Realized Price (in dollars)": "$3,500",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/takashi-murakami",
    slug: "takashi-murakami",
    name: "Takashi Murakami",
    "Artwork URL":
      "https://www.artsy.net/artwork/takashi-murakami-red-flowerball-3d-3",
    "Artwork ids (recently sold) (comma separated)": "5e277a7c2fb3ff000fd9f3c5",
    "Realized Price (in dollars)": "$2,500",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/takashi-murakami",
    slug: "takashi-murakami",
    name: "Takashi Murakami",
    "Artwork URL":
      "https://www.artsy.net/artwork/takashi-murakami-takashi-murakami-chaos-2013-takashi-murakami-prints",
    "Artwork ids (recently sold) (comma separated)": "5db342f22728aa00123d090f",
    "Realized Price (in dollars)": "$2,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/takashi-murakami",
    slug: "takashi-murakami",
    name: "Takashi Murakami",
    "Artwork URL":
      "https://www.artsy.net/artwork/takashi-murakami-takashi-murakami-time-bokan-pink-2006",
    "Artwork ids (recently sold) (comma separated)": "5ced7f8513d7b03d9e8ac09b",
    "Realized Price (in dollars)": "$1,650",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/takashi-murakami",
    slug: "takashi-murakami",
    name: "Takashi Murakami",
    "Artwork URL":
      "https://www.artsy.net/artwork/takashi-murakami-there-are-many-dokodemo-doors-and-we-can-go-anywhere-with-mr-fujiko-f-fujio-and-the-time-machine",
    "Artwork ids (recently sold) (comma separated)": "5e14aec4dcb381000ed93bfd",
    "Realized Price (in dollars)": "$7,219",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/tomoo-gokita",
    slug: "tomoo-gokita",
    name: "Tomoo Gokita",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": 654,
    "ROUNDED views to content from that artist (last month)": 650,
    "unique visitors to content from artist (last month)": 278,
    "ROUNDED unique visitors to content from artist (last month)": 270,
    "STR (last 12 months)": "98%",
    "Realized / estimate": "208%",
    "Highest realized price": "1.08M",
  },
  {
    url: "/artist/tomoo-gokita",
    slug: "tomoo-gokita",
    name: "Tomoo Gokita",
    "Artwork URL":
      "https://www.artsy.net/artwork/tomoo-gokita-uncovering-method",
    "Artwork ids (recently sold) (comma separated)": "5d13eb71e8447e001276c221",
    "Realized Price (in dollars)": "$8,500",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/tomoo-gokita",
    slug: "tomoo-gokita",
    name: "Tomoo Gokita",
    "Artwork URL":
      "https://www.artsy.net/artwork/tomoo-gokita-bombay-sapphire-number-1",
    "Artwork ids (recently sold) (comma separated)": "5bbe4210f742255beb2c79f6",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "/artist/tomoo-gokita",
    slug: "tomoo-gokita",
    name: "Tomoo Gokita",
    "Artwork URL": "https://www.artsy.net/artwork/tomoo-gokita-our-anniversary",
    "Artwork ids (recently sold) (comma separated)": "5cc8d5579cdd8007fd25644b",
    "Realized Price (in dollars)": "$280,000",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "",
    slug: "",
    name: "",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "",
    slug: "",
    name: "",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "",
    slug: "",
    name: "",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "",
    slug: "",
    name: "",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "",
    slug: "",
    name: "",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "",
    slug: "",
    name: "",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)": "Data source:",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "Data source: CiQ",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "",
    slug: "",
    name: "",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)":
      "https://artsy.looker.com/explore/artsy/artists?qid=afMxXgj9R0iQC6Yte3StuF&toggle=fil,vis",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
  {
    url: "",
    slug: "",
    name: "",
    "Artwork URL": "",
    "Artwork ids (recently sold) (comma separated)": "",
    "Realized Price (in dollars)": "",
    "views to content from that artist (last month)":
      "https://artsy.looker.com/explore/analytics/session_pages?qid=doFfIr7FX4GBqkn8xtmNkz&toggle=fil",
    "ROUNDED views to content from that artist (last month)": "",
    "unique visitors to content from artist (last month)": "",
    "ROUNDED unique visitors to content from artist (last month)": "",
    "STR (last 12 months)": "",
    "Realized / estimate": "",
    "Highest realized price": "",
  },
]
