import { GraphQLInputObjectType, GraphQLNonNull, GraphQLFloat } from "graphql"

const Near = new GraphQLInputObjectType({
  name: "Near",
  fields: {
    lat: {
      type: new GraphQLNonNull(GraphQLFloat),
    },
    lng: {
      type: new GraphQLNonNull(GraphQLFloat),
    },
    maxDistance: {
      type: GraphQLFloat,
    },
  } /*
  FIXME: Generated by the snake_case to camelCase codemod.
         Either use this to fix inputs and/or remove this comment.
  {
    const {
      maxDistance,
      ..._newFields
    } = newFields;
    const oldFields = {
      maxDistance: max_distance,
      ..._newFields
    };
  }
  */,
})

export default Near
