---
version: '2'
services:
  metaphysics:
    extends:
      file: common.yml
      service: metaphysics
    environment:
    - REDIS_URL=redis://metaphysics-redis:6379
    env_file: ../.env
    ports:
    - 5001:5001
    depends_on:
    - metaphysics-redis
  metaphysics-redis:
    image: redis
    ports:
    - 6379:6379
