version: "2"
services:
  metaphysics:
{% include 'templates/docker-compose-service.yml.j2' %}
    environment:
      - MEMCACHED_URL=metaphysics-memcached:11211
    env_file:
      - ../.env.shared
      - ../.env
    ports:
      - 3000:3000
    depends_on:
      - metaphysics-memcached
  metaphysics-memcached:
    image: memcached
    ports:
      - 11211:11211
