version: "2"
services:
  metaphysics:
{% include 'templates/docker-compose-service.yml.j2' %}
    command: ["yarn", "start"]
    env_file:
      - ../.env.shared
      - ../.env
    environment:
      GRAVITY_API_BASE: http://gravity:3000/api/v1
      GRAVITY_GRAPHQL_ENDPOINT: http://gravity:3000/api
      GRAVITY_API_URL: http://gravity:3000
      GRAVITY_ID: metaphysics-client-id
      GRAVITY_SECRET: metaphysics-client-secret
      MEMCACHED_URL: metaphysics-memcached:11211
    depends_on:
      - metaphysics-memcached
    ports:
      - 5001:5001
    volumes:
      - ../:/app
  metaphysics-memcached:
    image: memcached:1.4.34-alpine
    ports:
      - 11212:11211
