version: "2"
services:
  metaphysics:
    build:
      context: ../
      target: builder-base
    command: ["yarn", "start"]
    env_file:
      - ../.env.shared
      - ../.env.development
      - ../.env
    depends_on:
      - metaphysics-memcached
    ports:
      - 5001:5001
    volumes:
      - ../:/app
  metaphysics-memcached:
    image: memcached:1.4.34-alpine
