---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app-name: metaphysics
    app-phase: review
  name: infinite-discovery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metaphysics
    app.kubernetes.io/version: staging
    component: web
    layer: application
  name: metaphysics-web
  namespace: infinite-discovery
spec:
  selector:
    matchLabels:
      app: metaphysics
      component: web
      layer: application
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metaphysics
        app.kubernetes.io/version: staging
        component: web
        layer: application
      name: metaphysics-web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - foreground
      containers:
      - env:
        - name: PORT
          value: '3000'
        - name: DD_TRACER_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: STATSD_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_OPTIONS
          value: --max_old_space_size=768
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        envFrom:
        - configMapRef:
            name: metaphysics-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/metaphysics:infinite-discovery
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 10
        name: metaphysics-web
        ports:
        - containerPort: 3000
          name: mp-http
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: X-FORWARDED-PROTO
              value: https
            path: /health
            port: mp-http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
      dnsConfig:
        options:
        - name: ndots
          value: '1'
      dnsPolicy: ClusterFirst
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: metaphysics-web
  namespace: infinite-discovery
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metaphysics-web
  targetCPUUtilizationPercentage: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metaphysics
    component: web
    layer: application
  name: metaphysics-web-internal
  namespace: infinite-discovery
spec:
  ports:
  - name: mp-http
    port: 3000
    protocol: TCP
    targetPort: mp-http
  selector:
    app: metaphysics
    component: web
    layer: application
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,172.64.0.0/13,131.0.72.0/22,104.16.0.0/13,104.24.0.0/14,10.0.0.0/16,100.64.0.0/10
  name: metaphysics
  namespace: infinite-discovery
spec:
  ingressClassName: nginx
  rules:
  - host: metaphysics-infinite-discovery.artsy.net
    http:
      paths:
      - backend:
          service:
            name: metaphysics-web-internal
            port:
              name: mp-http
        path: /
        pathType: Prefix
