apiVersion: apps/v1
kind: Deployment
metadata:
  name: metaphysics-web
  labels:
    app: metaphysics
    layer: application
    component: web
    app.kubernetes.io/version: production
  namespace: default
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 20%
    type: RollingUpdate
  selector:
    matchLabels:
      app: metaphysics
      layer: application
      component: web
  template:
    metadata:
      labels:
        app: metaphysics
        layer: application
        component: web
        app.kubernetes.io/version: production
      name: metaphysics-web
    spec:
      containers:
      - name: metaphysics-web
        env:
        - name: PORT
          value: '3000'
        - name: DD_TRACER_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: STATSD_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_OPTIONS
          value: --max_old_space_size=768
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        envFrom:
        - configMapRef:
            name: metaphysics-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/metaphysics:production
        imagePullPolicy: Always
        ports:
        - name: mp-http
          containerPort: 3000
        resources:
          requests:
            cpu: 1000m
            memory: 768Mi
          limits:
            memory: 1.5Gi
        readinessProbe:
          httpGet:
            port: mp-http
            path: /health
            httpHeaders:
            - name: X-FORWARDED-PROTO
              value: https
          initialDelaySeconds: 5
          periodSeconds: 5
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 10
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
        - name: ndots
          value: '1'
      tolerations:
        - key: reserved
          operator: Equal
          value: spot
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - foreground
                - foreground-spot
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: metaphysics-web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metaphysics-web
  minReplicas: 10
  maxReplicas: 28
  targetCPUUtilizationPercentage: 60
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metaphysics
    layer: application
    component: web
  name: metaphysics-web-internal
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    name: mp-http
  selector:
    app: metaphysics
    layer: application
    component: web
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: metaphysics
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ externalIngressAllowSourceIP|join(',') }}
spec:
  ingressClassName: nginx
  rules:
  - host: metaphysics-production.artsy.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: metaphysics-web-internal
          servicePort: mp-http
