apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metaphysics-web
  namespace: default
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metaphysics
        layer: application
        component: web
      name: metaphysics-web
    spec:
      containers:
        - name: metaphysics-web
          env:
            - name: PORT
              value: "3000"
            - name: DD_TRACER_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: STATSD_HOST
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_OPTIONS
              value: "--max_old_space_size=768"
          envFrom:
            - configMapRef:
                name: metaphysics-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/metaphysics:staging
          imagePullPolicy: Always
          ports:
            - name: mp-http
              containerPort: 3000
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              memory: 1Gi
          readinessProbe:
            httpGet:
              port: mp-http
              path: /health
              httpHeaders:
                - name: X-FORWARDED-PROTO
                  value: https
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: metaphysics-nginx
          image: artsy/docker-nginx:1.14.2
          ports:
            - name: nginx-http
              containerPort: 80
            - name: nginx-https
              containerPort: 443
          readinessProbe:
            tcpSocket:
              port: nginx-http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          env:
            - name: "NGINX_DEFAULT_CONF"
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: metaphysics
          volumeMounts:
            - name: nginx-secrets
              mountPath: /etc/nginx/ssl
      volumes:
        - name: nginx-secrets
          secret:
            secretName: nginx-secrets
            defaultMode: 420
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                      - foreground

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: metaphysics-web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: metaphysics-web
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 95

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metaphysics
    layer: application
    component: web
  name: metaphysics-web
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ artsyNetWildcardSSLCert }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
spec:
  ports:
    - port: 443
      protocol: TCP
      name: https
      targetPort: mp-http
    - port: 80
      protocol: TCP
      name: http
      targetPort: mp-http
  selector:
    app: metaphysics
    layer: application
    component: web
  sessionAffinity: None
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metaphysics
    layer: application
    component: web
  name: metaphysics-web-internal
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: nginx-http
    - port: 443
      protocol: TCP
      name: https
      targetPort: nginx-https
  selector:
    app: metaphysics
    layer: application
    component: web
  type: ClusterIP
