---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metaphysics-web
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metaphysics
        layer: application
        component: web
      name: metaphysics-web
      namespace: default
    spec:
      containers:
      - name: metaphysics-web
        envFrom:
        - configMapRef:
            name: metaphysics-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/metaphysics:staging
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - foreground
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metaphysics
    layer: application
    component: web
  name: metaphysics-web
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::585031190124:server-certificate/2018-01-17_artsy-net-wildcard"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
spec:
  ports:
  - port: 443
    protocol: TCP
    name: https
    targetPort: 3000
  - port: 80
    protocol: TCP
    name: http
    targetPort: 3000
  selector:
    app: metaphysics
    layer: application
    component: web
  sessionAffinity: None
  type: LoadBalancer
