import { stripTags, markdownToText } from "lib/helpers"
import {
  GraphQLString,
  GraphQLObjectType,
  GraphQLFieldConfig,
  GraphQLEnumType,
  GraphQLNonNull,
} from "graphql"
import { ResolverContext } from "types/graphql"

export const metaName = (artist) => {
  if (artist.name) return stripTags(artist.name)
  return "Unnamed Artist"
}

const ArtistPageEnumType = new GraphQLEnumType({
  name: "ArtistPage",
  values: {
    ABOUT: { value: "ABOUT" },
    ARTWORKS: { value: "ARTWORKS" },
    AUCTION_RESULTS: { value: "AUCTION_RESULTS" },
    ARTIST_SERIES: { value: "ARTIST_SERIES" },
  },
})

const ArtistMetaType = new GraphQLObjectType<any, ResolverContext>({
  name: "ArtistMeta",
  fields: {
    description: {
      type: new GraphQLNonNull(GraphQLString),
      resolve: ({ artist, page }) => {
        const blurb = artist.blurb?.length
          ? ` ${markdownToText(artist.blurb).slice(0, 70)}`
          : ""

        switch (page) {
          case "ABOUT":
            return `Explore ${metaName(
              artist
            )}’s biography, achievements, artworks, auction results, and shows on Artsy.${blurb}`
          case "ARTWORKS":
            return `Discover and purchase ${metaName(
              artist
            )}’s artworks, available for sale. Browse our selection of paintings, prints, and sculptures by the artist, and find art you love.`
          case "AUCTION_RESULTS":
            return `Find out about ${metaName(
              artist
            )}’s auction history, past sales, and current market value. Browse Artsy’s Price Database for recent auction results from the artist.`
          case "ARTIST_SERIES":
            return `Explore ${metaName(
              artist
            )}’s series on Artsy and discover artworks available to collect. Browse the themes and artistic expressions that define ${metaName(
              artist
            )}’s career.`
        }
      },
    },
    title: {
      type: new GraphQLNonNull(GraphQLString),
      resolve: ({ artist, page }) => {
        switch (page) {
          case "ABOUT":
            return `${metaName(
              artist
            )} - Biography, Shows, Articles & More | Artsy`
          case "ARTWORKS": {
            if (EXPERIMENT_GROUP.includes(artist.id)) {
              return metaName(artist)
            }

            return `${metaName(artist)} - Artworks for Sale & More | Artsy`
          }
          case "AUCTION_RESULTS":
            return `${metaName(
              artist
            )} - Auction Results and Sales Data | Artsy`
          case "ARTIST_SERIES":
            return `${metaName(artist)} - Series | Artsy`
        }
      },
    },
  },
})

const Meta: GraphQLFieldConfig<void, ResolverContext> = {
  type: new GraphQLNonNull(ArtistMetaType),
  args: {
    page: { type: ArtistPageEnumType, defaultValue: "ABOUT" },
  },
  resolve: (artist, { page }) => {
    return { artist, page }
  },
}

export default Meta

// https://artsyproduct.atlassian.net/browse/DIA-1131
const EXPERIMENT_GROUP = [
  "abdoulaye-konate",
  "aboudia-1",
  "adolph-gottlieb",
  "agnes-martin",
  "alex-kanevsky",
  "alex-katz",
  "alexander-rodchenko",
  "alexandra-nechita",
  "alfred-gockel",
  "alice-neel",
  "alison-mosshart",
  "alma-thomas",
  "alyssa-monks",
  "amedeo-modigliani",
  "amoako-boafo",
  "amy-sillman",
  "andie-taylor",
  "andile-dyalvane",
  "andrea-kowch",
  "andreas-eriksson",
  "andrej-dubravsky",
  "andres-serrano",
  "andrew-cranston",
  "andy-goldsworthy-2",
  "andy-warhol",
  "angel-botello",
  "anna-delvey",
  "annie-leibovitz",
  "annie-morris",
  "anselm-kiefer",
  "anthony-james",
  "antonio-oba-1",
  "antonio-santin",
  "april-gornik",
  "arno-rafael-minkkinen-1",
  "atul-dodiya",
  "augustine-kofie",
  "avery-singer",
  "axel-hutte",
  "aya-takano",
  "barbara-kruger",
  "barnett-newman",
  "barry-mcgee",
  "bastiaan-woudt",
  "belkis-ayon",
  "bella-mcgoldrick",
  "benjamin-reichwald-bladee",
  "benjamin-shine",
  "berlinde-de-bruyckere",
  "bernard-buffet",
  "beth-cavener",
  "bill-braun",
  "bill-cunningham",
  "billie-zangewa",
  "bisa-butler",
  "bob-dylan",
  "bob-ross",
  "bosco-sodi",
  "bram-reijnders",
  "bruce-weber",
  "burton-morris",
  "cai-guo-qiang-cai-guo-qiang",
  "camille-henrot",
  "candida-hofer",
  "caroline-walker",
  "cecily-brown",
  "celia-paul",
  "chema-madoz",
  "chiharu-shiota",
  "chloe-wise",
  "christian-hook",
  "christina-kimeze",
  "christina-quarles",
  "christo",
  "chuck-close",
  "claire-tabouret",
  "claude-leveque",
  "claude-monet",
  "clementine-hunter",
  "crybaby-molly",
  "cy-twombly",
  "d-star-face",
  "dale-chihuly",
  "dan-hays",
  "dan-hillier",
  "daniele-raineri",
  "danielle-mckinney",
  "david-choe",
  "david-kracov",
  "david-lachapelle",
  "david-salle",
  "david-yarrow",
  "deana-lawson",
  "denis-fremond",
  "dennis-hopper",
  "devrim-erbil",
  "diane-arbus",
  "do-ho-suh",
  "don-ed-hardy",
  "donald-judd",
  "donald-sultan",
  "donatello",
  "dondi-white-donald-joseph-white",
  "dorit-levinstein",
  "dr-seuss",
  "duane-michals",
  "eddie-martinez",
  "edward-burtynsky",
  "edward-hopper",
  "edwin-schlossberg-1",
  "eelco-hilgersom",
  "el-anatsui",
  "eleanor-johnson",
  "elizabeth-langreiter",
  "elizabeth-peyton",
  "elly-smallwood",
  "emile-galle",
  "emilio-perez",
  "emily-kame-kngwarreye",
  "emily-mason",
  "emma-larsson",
  "emory-douglas",
  "eric-n-mack",
  "eric-sloane",
  "eric-stefanski",
  "eric-tucker",
  "ernest-concepcion",
  "erwin-wurm",
  "ethan-cook",
  "fabiano-millani",
  "faig-ahmed",
  "fairfield-porter",
  "farhad-moshiri",
  "felipe-pantone",
  "fernando-botero",
  "firelei-baez-1",
  "francesca-woodman",
  "francine-van-hove",
  "francisco-bartus",
  "franco-fontana",
  "frank-auerbach",
  "frank-bowling",
  "frank-lloyd-wright",
  "franz-kline",
  "frauke-alina-becker",
  "fred-herzog",
  "frederic-tuten",
  "frida-kahlo",
  "friedensreich-hundertwasser",
  "futura",
  "gabriel-moses",
  "gao-hang",
  "george-byrne",
  "george-platt-lynes",
  "george-rouy",
  "george-tice",
  "geraldine-javier",
  "gerhard-richter",
  "gideon-rubin",
  "gilles-bensimon",
  "giorgio-de-chirico",
  "gordon-parks",
  "grant-shaffer",
  "gregory-crewdson",
  "guillermo-lorca",
  "gustav-klimt",
  "h-r-giger",
  "hajime-sorayama",
  "hannah-hoch",
  "hans-bellmer",
  "hans-coper",
  "harland-miller",
  "heather-day",
  "heikki-marila",
  "helmut-newton",
  "henri-de-toulouse-lautrec",
  "henrietta-harris",
  "henry-darger",
  "henry-moore",
  "herb-ritts",
  "hieronymus-bosch",
  "hilary-pecis",
  "hilma-af-klint",
  "hiroshi-sugimoto",
  "hope-gangloff",
  "horst-p-horst",
  "howard-behrens",
  "howardena-pindell",
  "ida-ekblad",
  "idris-khan",
  "igshaan-adams",
  "ikeda-manabu",
  "imi-knoebel",
  "isabelle-brourman",
  "isamu-noguchi",
  "issy-wood",
  "itzchak-tarkay",
  "ivan-pokidyshev",
  "jack-penny",
  "jack-whitten",
  "jackson-pollock",
  "jake-grewal",
  "jamie-hewlett",
  "jane-waterous",
  "jane-wilson-1924-2015",
  "janet-fish",
  "jasper-johns",
  "jean-cocteau",
  "jean-jullien",
  "jean-michel-basquiat",
  "jean-michel-folon",
  "jeffrey-gibson",
  "jen-stark",
  "jennifer-packer",
  "jenny-saville",
  "jeppe-hein",
  "jerkface",
  "jess-allen",
  "jim-dine",
  "joan-cornella",
  "joan-miro",
  "joan-snyder",
  "joana-schneider",
  "joana-vasconcelos",
  "jockum-nordstrom",
  "jogen-chowdhury",
  "johanna-dumet",
  "john-buck",
  "john-currin",
  "john-kacere",
  "john-singer-sargent",
  "jon-burgerman",
  "jonas-wood",
  "jonathan-yeo",
  "jordan-casteel",
  "jose-parla",
  "josef-albers",
  "joseph-zbukvic",
  "joshua-smith",
  "judy-chicago",
  "julie-blackmon",
  "jun-kaneko",
  "justine-kurland",
  "jwan-yosef",
  "katherine-bernhardt",
  "katherine-bradford-1",
  "kaws",
  "kazuo-shiraga",
  "kehinde-wiley",
  "keith-haring",
  "kelly-wang-wang-jia-yi",
  "kenneth-gruenholtz",
  "kenneth-noland",
  "kenny-scharf",
  "kiki-smith",
  "kim-whanki",
  "kimmy-cantrell",
  "krishna-reddy",
  "larry-bell",
  "larry-clark",
  "le-corbusier",
  "lee-bae",
  "lee-k",
  "lei-xue",
  "leonard-peltier",
  "leonardo-da-vinci",
  "leonor-fini",
  "leroy-neiman",
  "lim-tze-peng",
  "linda-le-kinff",
  "lionel-smit",
  "lisa-yuskavage",
  "lisha-bai",
  "little-thunder",
  "loie-hollowell",
  "lorna-simpson",
  "louise-bourgeois",
  "luc-tuymans",
  "lucian-freud",
  "lucio-fontana",
  "lucy-liu",
  "ludwig-bemelmans",
  "luo-li-rong",
  "maggi-hambling",
  "malcolm-t-liepke",
  "manolo-valdes",
  "maqbool-fida-husain",
  "marc-henry",
  "marcel-duchamp",
  "margaret-kilgallen",
  "marie-laurencin",
  "marilyn-manson",
  "marilyn-minter",
  "mark-cohen",
  "mark-gonzales",
  "mark-lombardi",
  "mark-maggiori",
  "mark-nicdao",
  "mark-rothko",
  "marta-minujin",
  "martin-wong",
  "masami-ohno",
  "massimo-vitali",
  "matt-mccormick",
  "matthew-barney",
  "maurizio-cattelan",
  "max-lamb",
  "maya-hayuk",
  "miaz-brothers",
  "michael-carson",
  "michael-jang",
  "michael-kenna",
  "michael-kvium",
  "michael-mcgregor",
  "michelangelo-buonarroti",
  "michele-fletcher",
  "mickalene-thomas",
  "miles-johnston",
  "milton-avery",
  "minjung-kim",
  "miroslav-tichy",
  "mona-hatoum",
  "nan-goldin",
  "narsiso-c-martinez",
  "natasha-law",
  "nathan-paddison",
  "neil-welliver",
  "nelson-makamo",
  "nic-joly",
  "nick-alm",
  "nick-cave",
  "nick-thomm",
  "nicola-samori",
  "nicolas-party",
  "nicole-eisenman",
  "niki-de-saint-phalle",
  "noah-davis",
  "nobuyoshi-araki",
  "norman-rockwell",
  "odili-donald-odita",
  "okuda-san-miguel",
  "olga-de-amaral",
  "osgemeos",
  "otto-dix",
  "pacita-abad",
  "paolo-canevari",
  "parra",
  "patrick-heron",
  "patti-smith",
  "paul-delvaux",
  "paul-klee",
  "paula-rego",
  "pauline-boty",
  "pedro-cabrita-reis",
  "peggy-kuiper",
  "peggy-reavey",
  "pejac",
  "peter-doig",
  "peter-halley",
  "peter-hujar",
  "peter-mangone",
  "peter-max",
  "peter-voulkos",
  "petra-cortright",
  "philip-colbert",
  "piet-mondrian",
  "pino-daeni",
  "purvis-young",
  "rachel-whiteread",
  "rae-klein",
  "ragnar-kjartansson",
  "ralph-gibson",
  "ralph-steadman",
  "ram-kumar",
  "ramesh-gorjala",
  "ran-ortner",
  "rana-begum",
  "raoul-dufy",
  "rashid-johnson",
  "rc-gorman",
  "red-grooms",
  "ren-hang-ren-hang",
  "rene-magritte",
  "renee-french",
  "retna",
  "richard-butler",
  "richard-hambleton",
  "richard-misrach",
  "richard-mosse",
  "richard-phillips",
  "richard-prince",
  "richard-schmid",
  "richie-culver",
  "rita-ackermann",
  "rithika-merchant",
  "roa",
  "rob-pointon",
  "robert-bechtle",
  "robert-del-naja-aka-3d",
  "robert-indiana",
  "robert-motherwell",
  "robert-nava",
  "robert-rauschenberg",
  "roberto-de-la-rocha",
  "roby-dwi-antono",
  "ron-nagle",
  "ronald-ventura",
  "ronan-day-lewis",
  "ronnie-wood",
  "rose-wylie",
  "roy-de-forest",
  "roy-lichtenstein",
  "russell-young",
  "sally-mann",
  "salman-toor",
  "salvo",
  "sam-francis",
  "sandro-kopp",
  "saner",
  "sara-vide-ericson",
  "sasha-gordon",
  "satish-gujral",
  "saul-leiter",
  "sayed-haider-raza",
  "sean-scully",
  "sebastiao-salgado",
  "shara-hughes",
  "sharon-stone",
  "shepard-fairey",
  "shilpa-gupta",
  "shirin-neshat",
  "sho-shibuya",
  "shota-nakamura",
  "simon-berger",
  "simon-bull",
  "simon-hantai",
  "sir-winston-churchill",
  "slawn",
  "sonia-delaunay",
  "spencer-tunick",
  "stanley-mouse",
  "stanley-whitney",
  "sterling-ruby",
  "suchitra-mattai",
  "susan-mikula",
  "syd-solomon",
  "sylvester-stallone-1",
  "takashi-murakami",
  "takesada-matsutani",
  "tal-r",
  "tamara-de-lempicka",
  "tara-donovan",
  "thandiwe-muriu",
  "the-connor-brothers",
  "thierry-noir",
  "thomas-ruff",
  "thomas-trum",
  "tom-otterness",
  "tom-wesselmann",
  "toshio-saeki",
  "toyin-ojih-odutola",
  "tuan-vu",
  "tyler-shields",
  "vanessa-barragao",
  "vanessa-beecroft",
  "vanessa-stockard",
  "vasudeo-s-gaitonde",
  "vera-molnar-1",
  "vhils",
  "victor-vasarely",
  "vincent-van-gogh",
  "violeta-maya",
  "virgil-abloh",
  "vivian-maier",
  "wade-guyton",
  "walasse-ting-ding-xiong-quan",
  "wangechi-mutu",
  "wayne-thiebaud",
  "weegee",
  "werner-bronkhorst",
  "wes-lang",
  "will-barnet",
  "will-blood",
  "willem-de-kooning",
  "william-kentridge",
  "willy-verginer",
  "wolf-kahn",
  "wowser-ng",
  "yaacov-agam",
  "yamamoto-masao",
  "yinka-shonibare",
  "yoko-ono",
  "yoshida-hiroshi",
  "yuki-nara-nai-liang-you-xi",
  "zaha-hadid",
  "zanele-muholi",
  "zarina-1",
  "zoe-buckman",
]
